server:
   port: 8081
spring:
   application:
      name: reggie-old-deal
   datasource:
      druid:
         driver-class-name: org.postgresql.Driver
         url: jdbc:postgresql://postgresdb01.cdd6uaafebcj.ap-northeast-1.rds.amazonaws.com:5432/reggie
         username: postgres
         password: postgres
         max-active: 40
         max-wait: 150000
   output:
      ansi:
         enabled: ALWAYS
   jpa:
      hibernate:
         ddl-auto: update
         naming:
            physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      database: postgresql
      show-sql: true
      open-in-view: false
# 自定義傳入文件根目錄路徑
reggie:
   path: D:\VC Code\Java_KaiHatsu\file_In\