server:
  port: 8281
spring:
  application:
    name: reggie-take-out
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: ORACLECT
    password: ORACLECT
    hikari:
      maximum-pool-size: 30
      max-lifetime: 1500000
  output:
    ansi:
      enabled: ALWAYS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: logicDeleteFlg
      logic-delete-value: removed
      logic-not-delete-value: visible
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: jp.co.reggie.mbpdeal.entity
# 自定義傳入文件根目錄路徑
reggie:
  path: D:\VSCode\JavaKaiHatsu\ReggieFoods\