server:
  port: 8286
spring:
  application:
    name: reggie-take-out
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://52.199.163.241:5432/reggie
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 30
      max-lifetime: 1500000
  output:
    ansi:
      enabled: ALWAYS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: deleteFlg
      logic-delete-value: removed
      logic-not-delete-value: visible
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: jp.co.reggie.mbpdeal.entity
# 自定義傳入文件根目錄路徑
reggie:
  path: D:\VSCode\JavaKaiHatsu\ReggieFoods\